  [build]
  publish = "public/" # <-- ADD THIS LINE
  command = "pip install -r requirements.txt"
  functions = "netlify/functions/"
  python_version = "3.11.9"
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  included_files = ["app/**", "documents/**", ".env"]





# ... keep the rest of the file the same ...